framework:
    asset_mapper:
        # The paths to make available to the asset mapper.
        paths:
            - assets/

react:
    controllers_path: '%kernel.project_dir%/assets/build/react/controllers'

svelte:
    controllers_path: '%kernel.project_dir%/assets/build/svelte/controllers'
