"https://{all}/":
    type: upstream
    upstream: "app:http"

"http://{all}/":
    type: redirect
    to: "https://{all}/"


"https://{all}/.well-known/mercure":
    type: upstream
    upstream: "mercure:http"
