name: Symfony UX

on: [push, pull_request]

jobs:
    coding-style-php:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
                  tools: php-cs-fixer, cs2pr
            - name: php-cs-fixer
              run: php-cs-fixer fix --dry-run --format=checkstyle | cs2pr

    coding-style-js:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - run: yarn
            - run: yarn check-lint
            - run: yarn check-format

    tests-php-low-deps:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.2'
            - name: Chartjs
              run: |
                  cd src/Chartjs
                  composer update --prefer-lowest --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/simple-phpunit
            - name: Cropperjs
              run: |
                  cd src/Cropperjs
                  composer update --prefer-lowest --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/simple-phpunit
            - name: Dropzone
              run: |
                  cd src/Dropzone
                  composer update --prefer-lowest --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/simple-phpunit
            - name: LazyImage
              run: |
                  cd src/LazyImage
                  composer update --prefer-lowest --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/simple-phpunit

    tests-php8-low-deps:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
            - name: TwigComponent
              run: |
                  cd src/TwigComponent
                  composer update --prefer-lowest --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/simple-phpunit
            - name: LiveComponent
              run: |
                  cd src/LiveComponent
                  php ../../.github/build-packages.php
                  composer update --prefer-lowest --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/simple-phpunit

    tests-php-high-deps:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.0'
            - name: Chartjs
              run: |
                  cd src/Chartjs
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/simple-phpunit
            - name: Cropperjs
              run: |
                  cd src/Cropperjs
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/simple-phpunit
            - name: Dropzone
              run: |
                  cd src/Dropzone
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/simple-phpunit
            - name: LazyImage
              run: |
                  cd src/LazyImage
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/simple-phpunit
            - name: TwigComponent
              run: |
                  cd src/TwigComponent
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/simple-phpunit
            - name: LiveComponent
              run: |
                  cd src/LiveComponent
                  php ../../.github/build-packages.php
                  composer update --prefer-dist --no-interaction --no-ansi --no-progress
                  php vendor/bin/simple-phpunit

    tests-js:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - run: yarn
            - run: yarn test
